openapi: 3.0.0
info:
  title: Sample API
  description: A short description of API
  termsOfService: http://example.com/terms/
  contact: 
    name: API support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://dev.sample-server.com/v1
    description: Prod
paths:
  /users:
    get:
      tags:
        - users
      summary: Get
      description: Get user
      parameters: []
      responses:
        '200':
          description: A JSON
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User' # 参照するモデル
                example:
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jane Doe
components:
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
