web:
  image: nginx
  volumes:
    - ../out:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "8080:80"
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
      
